# Generated by Django 2.1.1 on 2018-09-18 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github_id',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[\\S_-]+$', message='Only letters, numbers, underscores and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='org_id',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='MCTC Student ID must be 8 numbers')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='star_id',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[a-z]{2}\\d{4}[a-z]{2}$', message='Star ID must be in the pattern ab1234cd')]),
        ),
    ]
