# Generated by Django 2.1.1 on 2018-09-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=200)),
                ('display', models.CharField(blank=True, max_length=200)),
                ('regex', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('hyperlink', models.CharField(blank=True, max_length=200)),
                ('required', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
