# Generated by Django 2.1.1 on 2018-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180920_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='no_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='hyperlink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
