# Generated by Django 2.1.1 on 2018-09-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180920_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='omit_from_forms',
            field=models.BooleanField(default=False),
        ),
    ]
