# Generated by Django 2.1.1 on 2018-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180922_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingclass',
            name='semester_human_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
