# Generated by Django 2.1.1 on 2018-09-24 18:16

from django.db import migrations, models

import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180922_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grading_batch',
            field=models.UUIDField(default=uuid.uuid4()),
            preserve_default=False,
        ),
    ]
