# Generated by Django 2.1.1 on 2018-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_grade_grading_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grading_batch',
            field=models.UUIDField(blank=True),
        ),
    ]
