# Generated by Django 2.1.1 on 2018-09-24 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180924_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
