# Generated by Django 2.1.1 on 2018-09-24 18:41

from django.db import migrations, models

import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_grade_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grading_batch',
        ),
        migrations.AddField(
            model_name='grade',
            name='batch',
            field=models.UUIDField(default=uuid.uuid4()),
            preserve_default=False,
        ),
    ]
