# Generated by Django 2.1.1 on 2018-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180924_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='generated_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='instructor_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
