# Generated by Django 2.1.1 on 2018-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180924_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='week',
            field=models.IntegerField(unique=True),
        ),
    ]
