# Generated by Django 2.1.1 on 2018-09-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180924_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('week', 'programming_class')},
        ),
    ]
