# Generated by Django 2.1.1 on 2018-09-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180924_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='week',
            field=models.IntegerField(),
        ),
    ]
