# Generated by Django 2.1.1 on 2018-09-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180924_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.GraderModule'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='programming_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ProgrammingClass'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='programming_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ProgrammingClass'),
        ),
    ]
