# Generated by Django 2.1.1 on 2018-10-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_student_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingBatch',
            fields=[
                ('batch', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='grader',
        ),
        migrations.DeleteModel(
            name='GraderModule',
        ),
    ]
