# Generated by Django 2.1.1 on 2018-10-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181023_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingbatch',
            old_name='batch',
            new_name='id',
        ),
    ]
