# Generated by Django 2.1.1 on 2018-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181024_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingbatch',
            name='things_to_grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
