# Generated by Django 2.1.1 on 2018-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_gradingbatch_things_to_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingbatch',
            name='graded',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
