# Generated by Django 2.1.1 on 2018-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_gradingbatch_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingbatch',
            name='graded',
            field=models.IntegerField(default=0),
        ),
    ]
