# Generated by Django 2.1.1 on 2018-10-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181024_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingbatch',
            old_name='graded',
            new_name='processed',
        ),
    ]
