# Generated by Django 2.1.1 on 2018-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20181024_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
