# Generated by Django 2.1.1 on 2018-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_grade_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
