# Generated by Django 2.1.1 on 2018-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20181025_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
