# Generated by Django 2.1.1 on 2018-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20181025_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='github_commit_hash',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
