# Generated by Django 2.1.1 on 2018-10-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181029_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentprogrammingclass',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentprogrammingclass',
            name='programming_class',
        ),
        migrations.RemoveField(
            model_name='studentprogrammingclass',
            name='programming_class',
        ),
        migrations.RemoveField(
            model_name='studentprogrammingclass',
            name='student',
        ),
        migrations.AddField(
            model_name='assignment',
            name='programming_classes',
            field=models.ManyToManyField(to='api.ProgrammingClass'),
        ),
        migrations.AddField(
            model_name='student',
            name='programming_classes',
            field=models.ManyToManyField(to='api.ProgrammingClass'),
        ),
        migrations.DeleteModel(
            name='AssignmentProgrammingClass',
        ),
        migrations.DeleteModel(
            name='StudentProgrammingClass',
        ),
    ]
