# Generated by Django 2.1.1 on 2018-10-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181029_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='programming_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.ProgrammingClass'),
            preserve_default=False,
        ),
    ]
