# Generated by Django 2.1.1 on 2018-11-02 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_grade_programming_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='programming_classes',
            field=models.ManyToManyField(blank=True, to='api.ProgrammingClass'),
        ),
        migrations.AlterField(
            model_name='programmingclass',
            name='semester_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^20\\d{2}0[135]$', message='Must be 6 numbers, year+semester code e.g. Fall 2019 is 201901')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='programming_classes',
            field=models.ManyToManyField(blank=True, to='api.ProgrammingClass'),
        ),
    ]
