# Generated by Django 2.1.1 on 2018-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20181102_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programming_classes',
            field=models.ManyToManyField(to='api.ProgrammingClass'),
        ),
    ]
