# Generated by Django 2.1.1 on 2018-11-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20181102_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='error',
            new_name='ag_error',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='reviewed',
        ),
    ]
