# Generated by Django 2.1.1 on 2018-11-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20181104_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='last_success',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('GR', 'Succesfully graded'), ('SE', 'Error in student code or code not found'), ('AE', 'Autograder errored')], default='GR', max_length=2),
        ),
    ]
