# Generated by Django 2.1.1 on 2018-11-06 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20181104_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingbatch',
            name='programmingClass',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.ProgrammingClass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='github_commit_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
