# Generated by Django 2.1.1 on 2018-09-13 01:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('github_base', models.CharField(max_length=200)),
                ('instructor_repo', models.CharField(max_length=200)),
                ('d2l_gradebook_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_report', models.TextField()),
                ('instructor_comments', models.TextField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autograder.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pants', max_length=100)),
                ('grader', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='MCTC Student ID must be 8 numbers')])),
                ('name', models.CharField(max_length=200)),
                ('github_id', models.CharField(blank=True, max_length=200)),
                ('star_id', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^[a-z]{2}\\d{4}[a-z]{2}$', message='Star ID must be in the pattern ab1234cd')])),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autograder.Student'),
        ),
    ]
