# Generated by Django 2.1.1 on 2018-09-12 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('github_name', models.CharField(max_length=200)),
                ('star_id', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('.+{8}')])),
            ],
        ),
    ]
