# Generated by Django 2.1.1 on 2018-09-12 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='star_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-z]{2}\\d{4}[a-z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$]')]),
        ),
    ]
