# Generated by Django 2.1.1 on 2018-09-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_assignment_programming_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programming_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autograder.ProgrammingClass'),
        ),
    ]
