# Generated by Django 2.1.1 on 2018-09-12 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_auto_20180912_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='star_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-z]{2}\\d{4}[a-z]{2}$', message='Star ID must be in the pattern ab1234cd')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$]', message='MCTC Student ID must be 8 numbers')]),
        ),
    ]
