# Generated by Django 2.1.1 on 2018-09-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0004_auto_20180918_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autograder.GraderModule'),
        ),
    ]
