# Generated by Django 2.1.1 on 2018-09-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0005_assignment_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='github_name',
            new_name='github_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='d2l_gradebook_url',
            field=models.CharField(default='sdfsfd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructor_repo',
            field=models.CharField(default='sdfsdf', max_length=200),
            preserve_default=False,
        ),
    ]
