# Generated by Django 2.1.1 on 2018-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('github_base', models.CharField(max_length=200)),
                ('instructor_repo', models.CharField(max_length=200)),
                ('d2l_gradebook_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
